// Code generated by github.com/infraboard/mcube
// DO NOT EDIT

package rule

import (
	"bytes"
	"fmt"
	"strings"
)

// ParseSYNC_MODEFromString Parse SYNC_MODE from string
func ParseSYNC_MODEFromString(str string) (SYNC_MODE, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := SYNC_MODE_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown SYNC_MODE: %s", str)
	}

	return SYNC_MODE(v), nil
}

// Equal type compare
func (t SYNC_MODE) Equal(target SYNC_MODE) bool {
	return t == target
}

// IsIn todo
func (t SYNC_MODE) IsIn(targets ...SYNC_MODE) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t SYNC_MODE) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *SYNC_MODE) UnmarshalJSON(b []byte) error {
	ins, err := ParseSYNC_MODEFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}
