// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: apps/notifier/pb/notifer.proto

package notifier

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RPCClient is the client API for RPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPCClient interface {
	// 接收报警信息，进行转换
	SendWechatRobot(ctx context.Context, in *NotificationInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 发送报警信息到企业微信 Robot
	TransFormToWechat(ctx context.Context, in *NotificationWechat, opts ...grpc.CallOption) (*Message, error)
}

type rPCClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCClient(cc grpc.ClientConnInterface) RPCClient {
	return &rPCClient{cc}
}

func (c *rPCClient) SendWechatRobot(ctx context.Context, in *NotificationInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/robot.notifier.RPC/SendWechatRobot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) TransFormToWechat(ctx context.Context, in *NotificationWechat, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/robot.notifier.RPC/TransFormToWechat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCServer is the server API for RPC service.
// All implementations must embed UnimplementedRPCServer
// for forward compatibility
type RPCServer interface {
	// 接收报警信息，进行转换
	SendWechatRobot(context.Context, *NotificationInfo) (*emptypb.Empty, error)
	// 发送报警信息到企业微信 Robot
	TransFormToWechat(context.Context, *NotificationWechat) (*Message, error)
	mustEmbedUnimplementedRPCServer()
}

// UnimplementedRPCServer must be embedded to have forward compatible implementations.
type UnimplementedRPCServer struct {
}

func (UnimplementedRPCServer) SendWechatRobot(context.Context, *NotificationInfo) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendWechatRobot not implemented")
}
func (UnimplementedRPCServer) TransFormToWechat(context.Context, *NotificationWechat) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransFormToWechat not implemented")
}
func (UnimplementedRPCServer) mustEmbedUnimplementedRPCServer() {}

// UnsafeRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCServer will
// result in compilation errors.
type UnsafeRPCServer interface {
	mustEmbedUnimplementedRPCServer()
}

func RegisterRPCServer(s grpc.ServiceRegistrar, srv RPCServer) {
	s.RegisterService(&RPC_ServiceDesc, srv)
}

func _RPC_SendWechatRobot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).SendWechatRobot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/robot.notifier.RPC/SendWechatRobot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).SendWechatRobot(ctx, req.(*NotificationInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_TransFormToWechat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationWechat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).TransFormToWechat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/robot.notifier.RPC/TransFormToWechat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).TransFormToWechat(ctx, req.(*NotificationWechat))
	}
	return interceptor(ctx, in, info, handler)
}

// RPC_ServiceDesc is the grpc.ServiceDesc for RPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "robot.notifier.RPC",
	HandlerType: (*RPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendWechatRobot",
			Handler:    _RPC_SendWechatRobot_Handler,
		},
		{
			MethodName: "TransFormToWechat",
			Handler:    _RPC_TransFormToWechat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/notifier/pb/notifer.proto",
}
